eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
    instance:
      prefer-ip-address: true
    healthcheck :
      enabled : true

okta:
  oauth2:
    issuer: https://dev-86454026.okta.com/oauth2/default
    audience: api://default
